### ISSUE TITLE
Not functioning on LP

### ISSUE THREAD

**Issue by LonnieReeder** [tasks/locale-plugin#1]
I can get the plugin to work just fine on my Samsung gal s3 running kitkat. But it will not function on my tablet, Asus transformer tf300t running LP 5.1.1, which is a custom ROM, Katkiss for the tf300t.. I am using the same vertrsion of Taker on both devices.

**Comment by abaker** [comment]
Could you check if you have the latest tasks beta and v0.2.0 of the tasker plugin? I released updates for both yesterday to fix an issue
