### ISSUE TITLE
Filter names not shown on configuration edit screen

### ISSUE THREAD

**Issue by disser** [tasks/locale-plugin#2]
<img src="https://cloud.githubusercontent.com/assets/94499/9141333/bb59bfac-3cec-11e5-9cce-ab260fa84025.png" width=300>

LG G3, Android 5.0.1
Tasker 4.7u3
Tasks 4.7.17
Tasks Locale Plug-in 0.2.0

**Comment by abaker** [comment]
Thanks, going to release Tasks 4.7.18 now to fix this
